export ANDROID_SDK_PATH=$HOME/android-sdk-linux
export ANDROID_SDK_TOOL_PATH=${ANDROID_SDK_PATH}/tools
export ANDROID_SDK_PLATFORM_TOOL_PATH=${ANDROID_SDK_PATH}/platform-tools
export PATH=${ANDROID_SDK_PLATFORM_TOOL_PATH}:${PATH}
export PATH=${ANDROID_SDK_TOOL_PATH}:${PATH}
